- bullet-train-core.js
Logging out the flags to the console is a security hole. We don't want to push that information into various logging apps.
> Removes console.log of response

- bullet-train-core.js
- package.json
1 - we were using a singleton collection of flags, which get updated after every request to the API. This is pretty bad as it introduces a possible race condition where user a gets user b's flags
2 - we were using some weird patterns to support binding this/self
3 - we were only returning remote configs if enabled was true, pretty certain we removed that field a while back
> Make bullet-train flags stateless, fix binding.

- flagsmith-core.js
- package.json
fallback to require('node-fetch').default due to https://github.com/node-fetch/node-fetch/issues/450
> fallback to require('node-fetch').default

- sdk/index.ts
- sdk/utils.ts
This PR fixes 2 issues: 
1. Getting identity flags was previously throwing a 415 due to the lack of the Content-Type header
2. Traits were being generated incorrectly due to the use of `Object.values` instead of `Object.entries`
> Fix traits logic

- index.d.ts
The `setTrait` method returns a promise but the interface makes it look like a synchronous operation. This could lead to race conditions if the call is not awaited before a `getValue` with a userId is executed.
> Fix setTrait Return Type

- example/package-lock.json
- example/server/api/index.js
- example/server/index.js
- package-lock.json
- sdk/index.ts
- sdk/types.ts
- tests/sdk/utils.ts
- Node cache may return undefined on cache.get, we presumed it would always return flags
- node-cache's type definitions are incorrect and claim you have to always provide a TTL in cache.set, in reality it falls back to stdTtl
- app.server.address().port crashed the app for me
I've adjusted the example and confirmed that cache is getting set and used
> Fix types to support node cache

- sdk/index.ts
If `enableLocalEvaluation` is set to true, the rejection from `this.environmentPromise` may not be handled leading to a crash in the parent nodejs process which is using this library.
(Crash log for reference)
```
node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "error: timeout".] {
code: 'ERR_UNHANDLED_REJECTION'
}
```
"error: timeout" originates from https://github.com/Flagsmith/flagsmith-nodejs-client/blob/8efdc989ed5042ee3a9f5c4c8ad85885d05724de/sdk/utils.ts#L27
> fix(getIdentityFlags): Propagate errors from inner promises in sdk

- sdk/index.ts
Currently, there's no externally expose API to cleanup the `setInterval()` created by the polling manager class. This PR introduces a external close() method to provide this functionality
> Provide cleanup method for polling manager

- sdk/index.ts
- tests/sdk/data/environment.json
- tests/sdk/flagsmith-identity-flags.test.ts
- tests/sdk/flagsmith.test.ts
Currently, when using local evaluation, multivariate flag evaluations are not working since we're not passing the identity ID to the engine when evaluating the flags. 
This PR ensures that the identityID is passed.
> Fix issue with local evaluation of multivariate flags

- sdk/index.ts
- tests/engine/unit/utils/utils.test.ts
Fixes a bug where MV values were not consistent on different evaluations for the same identity. This was caused by the fact that we were using the (transient) identityUuid property of the identity rather than the (idempotent) compositeKey. 
Note that as part of this work, I've also added the missing tests for the percentage value hashing logic.
> Ensure local evaluation returns consistent MV values

- sdk/index.ts
- sdk/utils.ts
- tests/engine/unit/utils/utils.test.ts
- tests/sdk/flagsmith.test.ts
This fixes an issue where the client was not falling back to the defaultFlagHandler when a timeout was reached requesting the data from the API. 
To resolve this, I have ensured that the timeout is used on requests to the API (as I believe it was not previously as `timeout` does not seem to be a valid option to provide to the `node-fetch` library). I have also adjusted the logic slightly such that each request implements the timeout, separate from the retry logic which is how our other libraries handle it.
> Fix timeout not using default flags

- flagsmith-engine/identities/models.ts
- flagsmith-engine/segments/evaluators.ts
- tests/engine/unit/segments/segment_evaluators.test.ts
Fixes https://github.com/Flagsmith/flagsmith/issues/2186 for Node.js client. MUST be released as part of a new major version.
> Ensure percentage split evaluations are consistent

- .github/workflows/publish.yml
Workflow was running npm publish, this would not attempt to build the application resulting in an empty deployment to NPM
> Fix deploy action

- flagsmith-engine/features/models.ts
We had the following use-case: around 70 feature flags, most of which are either fully turned on or off.
Because `md5` hash is calculated for every feature flag, `getIdentityFlags` with local evaluation ended up taking 30-40ms.
The pr lazily calls `getHashedPercentateForObjIds` only when needed, and skips it for cases when it's not necessary (0 and 100%). With the patch `getIdentityFlags` executes in ~3ms.
Please let me know if something is missing or needs changing. Have a nice day!
> Lazily calculate the hash

- package-lock.json
- package.json
Version 3.1.1
Fixes issue with the default request timeout no being set to 10 seconds.
> Chore: Bump version to 3.1.1

- sdk/index.ts
- sdk/offline_handlers.ts
- sdk/types.ts
- tests/sdk/data/offline-environment.json
- tests/sdk/flagsmith.test.ts
- tests/sdk/offline-handlers.test.ts
- tests/sdk/utils.ts
Implement offline mode for NodeJs SDK
Further documentation in the issue ticket https://github.com/Flagsmith/flagsmith/issues/2024
> feat: offline-mode

- sdk/analytics.ts
- tests/sdk/analytics.test.ts
This bug was reported by a customer - see the added test for an example on how to reproduce it. There might be a smarter way to write the test, haven't used jest much before.
The bugfix is essentially a mutex to ensure that we're only ever making one request at a time to flush analytics data.
> fix: only flush analytics once if requested concurrently

- flagsmith-engine/segments/models.ts
- tests/engine/unit/segments/segments_model.test.ts
This PR fixes #149 . 
Note that in keeping with [the python engine implementation](https://github.com/Flagsmith/flagsmith-engine/blob/main/flag_engine/segments/evaluator.py#L129), I ensured that `NOT_CONTAINS` returns false for non string values.
> fix: error evaluating CONTAINS / NOT_CONTAINS for null traits

- flagsmith-engine/segments/models.ts
- tests/engine/unit/segments/segments_model.test.ts
This PR fixes an issue where the regex operator would throw an exception if the trait value was null. 
Note that this PR also converts any non-string traits to strings to match the behaviour of the python client as seen [here](https://github.com/Flagsmith/flagsmith-engine/blob/main/flag_engine/segments/evaluator.py#L136-L139).
> fix: handle null traits for regex evaluations

- sdk/utils.ts
Once the fetch request completes, it is no longer necessary to wait for the timeout. Cancel it to clear the async stack
This is specifically an issue when using this library from within an AWS lambda, as the default handling waits for an empty event loop before allowing the lambda to complete.
> callbackWaitsForEmptyEventLoop – Set to false to send the response right away when the callback runs, instead of waiting for the Node.js event loop to be empty. If this is false, any outstanding events continue to run during the next invocation.
https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html
This seemed like a quick change that would be correct for other runtime environments, so I submitted this PR.
> Cancel timeout when it is no longer needed

- flagsmith-engine/identities/models.ts
- flagsmith-engine/identities/traits/models.ts
- sdk/index.ts
- sdk/types.ts
- sdk/utils.ts
- tests/sdk/data/identity-with-transient-traits.json
- tests/sdk/data/transient-identity.json
- tests/sdk/flagsmith-identity-flags.test.ts
- tests/sdk/utils.ts
Closes https://github.com/Flagsmith/flagsmith-nodejs-client/issues/156
> feat: Support transient identities and traits

- .github/workflows/pull_request.yaml
- flagsmith-engine/features/models.ts
- flagsmith-engine/identities/models.ts
- flagsmith-engine/segments/models.ts
- flagsmith-engine/utils/hashing/index.ts
- index.ts
- package-lock.json
- package.json
- tests/engine/e2e/engine.test.ts
- tests/engine/unit/utils/utils.test.ts
- tests/sdk/offline-handlers.test.ts
- tsconfig.json
The current beta version of this library doesn't work when used from ESM:
```js
// test.mjs
import Flagsmith, { EnvironmentModel } from "./build/esm/index.js"
console.log(Flagsmith, EnvironmentModel)
```
```console
% node index.mjs
file:///Users/rolodato/source/flagsmith/flagsmith-nodejs-client/test/node_modules/flagsmith-nodejs/build/esm/flagsmith-engine/identities/models.js:2
const { v4: uuidv4 } = require('uuid');
^
ReferenceError: require is not defined in ES module scope, you can use import instead
at file:///Users/rolodato/source/flagsmith/flagsmith-nodejs-client/test/node_modules/flagsmith-nodejs/build/esm/flagsmith-engine/identities/models.js:2:24
at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:337:24) …
```
> feat!: Remove all uses of CJS, add named Flagsmith export

- index.ts
This code is impossible to write without exporting the `LocalFileHandler` and `BaseOfflineHandler` types: https://docs.flagsmith.com/clients/server-side?language=nodejs#using-an-offline-handler
> fix: Export offline handler types

- package-lock.json
- package.json
- sdk/index.ts
- sdk/types.ts
- tests/sdk/flagsmith-cache.test.ts
- tests/sdk/utils.ts
The `FlagsmithCache` interface is unnecessarily complicated:
* `has` is never used by the SDK, it is only used in tests. This change removes it.
* The return value of `set` is never used by the SDK, and serves no purpose. This changes `set` to be of type `Promise<void>`.
* `set` accepts a `ttl` parameter but the SDK never actually uses it. This change removes it.
* The return type of `get` used to be `Promise<Flags | undefined> | undefined`. In practice, the SDK always awaits this value so it should be `Promise<Flags | undefined>`, which is what this change uses.
The `Flagsmith` constructor also checks that the supplied cache has the same methods as the ones required by `FlagsmithCache`. This check is not thorough enough to be useful and should be done by typechecking. Also, this checking …
> feat: Simplify FlagsmithCache interface

- package-lock.json
- package.json
- sdk/models.ts
Couldn't figure out how to add a test case to https://github.com/Flagsmith/engine-test-data/blob/e43097ee273fa63dbb9589c02f89df3d10b51044/data/environment_n9fbf9h3v4fFgH3U3ngWhb.json - verified manually with the following test:
```js
// test.cjs
const Flagsmith = require('./build/cjs').Flagsmith
const flagsmith = new Flagsmith({
environmentKey: 'LMVKS7tqAcQrjtsDWLoe7g',
});
const flags = await flagsmith.getEnvironmentFlags();
const value = flags.getFeatureValue('zero');
console.log(value);
```
Before:
```
rolodato@rolosmith flagsmith-nodejs-client % bun run build && bun test.cjs
$ rm -rf ./build
$ tsc -b tsconfig.cjs.json tsconfig.esm.json && echo '{"type": "commonjs"}'> build/cjs/package.json
undefined
```
After:
```
rolodato@rolosmith flagsmith-nodejs-client % bun run build && bun …
```
> fix: Return 0 as number flag value instead of undefined

- index.ts
- package-lock.json
- package.json
- sdk/analytics.ts
- sdk/index.ts
- tests/sdk/analytics.test.ts
- tests/sdk/utils.ts
Currently, we only support having the analytics API on the same host as the flags/identities endpoints. This is not the case when using the Edge Proxy, which does not accept analytics requests.
This change allows configuring an arbitrary analytics endpoint URL, and exports the `AnalyticsProcessor` + `AnalyticsProcessorOptions` types to allow manual analytics management.
> feat: Allow configuring analytics API endpoint separate from flags API

- sdk/models.ts
Hi :wave:,
I've recently started using this library at work and was surprised to see the return type of `getFeatureValue` was `any`. I replaced that with a new type that represents the type of the `value` field of `BaseFlag`, and replaced a few more uses of `any` in the file where there were possible replacements. The only uses of `any` left are for the incoming data retrieved as json which would be more involved to fix.
> Remove uses of `any` in models.ts

- flagsmith-engine/index.ts
- index.ts
Hi :wave:,
I'm experimenting with making a custom offline handler and was surprised that this class was not exported already, since it seems fairly necessary when using `FeatureStateModel`. For now I've had to  copy `FeatureModel` into my app code so it'd be great to have this exported so I didn't need to.
> feat: Export FeatureModel to enable custom offline handler

- .github/workflows/publish.yml
- .github/workflows/pull_request.yaml
- .prettierrc.cjs
Update prettier configuration to indent yaml files with 2 spaces instead of 4.
> chore: update indentation

- .github/workflows/conventional-commit.yml
Removes unnecessary usage of depot runner for conventional commit validation workflow
> ci: remove depot runner from conventional-commit workflow
